### ISSUE TITLE
Deleted photos are not physically deleted from the filesystem

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#102]
As a result, they take up extra space. I would also like them to be removed from the general list of photos on the main page. At least the logic of their presence in that place is not clear.

**Comment by Katarn** [comment]
Offtop. Will it be okay if I write in Russian? It seems that I can more accurately convey the thought.

**Comment by impworks** [comment]
Deleted media is still kept on disk so that it is possible to restore any changeset, and no data is ever lost.

However, storage space is worth the consideration. Maybe there should be a “remove forever” checkbox only available to the admin?

**Comment by Katarn** [comment]
Yes, that would be logical. (And do not forget that deleted photos should not be shown on the main page.)

Alternatively, you can delete them after some time, for example, after a month.

**Comment by impworks** [comment]
There is now a checkbox "remove the file irreversibly to save disk space". It's available to the admin only. If the file has been removed completely, all its changesets become irreversible as well since now there's nothing to restore.

The smallest thumbnail (`*.sm.jpg`) is still kept even after deleting the file completely, so that it does not impair the changesets UI. These files are usually below 10kb in size, so this should not cause a problem with disk space.
