### ISSUE TITLE
Incorrect layout in Firefox

### ISSUE THREAD

**Issue by redmanmale** [impworks/bonsai#63]
In latest Firefox login page looks like this.

![pic](https://puu.sh/CNApc/f15c31382b.png)

**Comment by impworks** [comment]
@redmanmale looks like you don't have the styles built. Are you using `dotnet run` instead of opening the project in VS? If so, please do the following:

1. Install `NodeJS` of the latest version
2. Go to the application's root directory and execute `npm install`
3. Then execute `npm install -g gulp-cli`
4. Then execute `gulp build`

This should get all the styles and scripts properly built.

I will add this to the installation guide.

**Comment by redmanmale** [comment]
Yeah, thank you, it helps.
I should've look better before asking.

**Comment by impworks** [comment]
@redmanmale it's alright, the installation guide would benefit from some more clarity.
